menu:
  Home: /
  Posts: /chronological-ordering
  Archives: /the-archives-the-archives-the-archives
rss: /atom.xml
banner: ../assets/salty_mountains.png

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 4
# Footer
# Hacky-workaround for header
copyright: |-
  <style>header nav{background-color: black; padding: 0px 20px;}</style>

# Sidebar
sidebar: left
widgets:
- category
- tag
- recent_posts
- archive
- tagcloud

# Miscellaneous
favicon: /assets/Dendy.jpg

# Header links
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links:
  github: https://github.com/Denperidge-Redpencil
  external-link: https://denperidge.com
